# Generated by Django 6.0.4 on 2026-05-04 04:26

import users.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_aadhar_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aadhar_card_number',
            field=users.fields.EncryptedCharField(blank=True, max_length=12),
        ),
    ]
